[package]
name = "otel-tests-macro"
version = "0.1.0"
edition = "2021"
description = "Internal #[otel_test] macro crate for otel-tests"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }
